---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "quilt2"
description: |
  QUILT2 is an R and C++ program for fast genotype imputation from low-coverage sequence using a large reference panel.
  QUILT2 is accurate and versatile, able to handle imputation from short read, long read, ancient DNA and cell-free DNA from NIPT.
keywords:
  - imputation
  - low-coverage
  - long-read
  - genotype
  - genomics
  - vcf
tools:
  - "quilt2":
      description: "Rapid and accurate genotype imputation from low coverage short read, long read, and cell free DNA sequence."
      homepage: "https://github.com/rwdavies/quilt"
      documentation: "https://github.com/rwdavies/quilt"
      tool_dev_url: "https://github.com/rwdavies/quilt"
      doi: ""
      licence: ['GPL v3']
      identifier: ""

input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  
  ## TODO nf-core: Delete / customise this example input
    - bam:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_25722"
          - edam: "http://edamontology.org/format_2573"
          - edam: "http://edamontology.org/format_3462"
          

## TODO nf-core: Add a description of all of the variables used as output
output:
  - bam:
  #Only when we have meta
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  ## TODO nf-core: Delete / customise this example output
    - "*.bam":
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_25722"
          - edam: "http://edamontology.org/format_2573"
          - edam: "http://edamontology.org/format_3462"
          
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@LouisLeNezet"
maintainers:
  - "@LouisLeNezet"
